# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8080/user/create
Content-Type: application/json

{
"account": "bjj3036",
  "password": "qwer1234",
  "name": "baejunjae",
  "email": "aaa@naver.com",
  "phone": "010-0000-1111"
}

###
POST http://localhost:8080/post/create
Content-Type: application/json

{
"userId": "1",
"title": "게시물3",
  "content": "얼마나 너의 무한한 그것을 생의 그들의 동산에는 얼음 생명을 것이다. 있으며, 내려온 두기 그것을 오아이스도 사막이다. 산야에 물방아 그림자는 위하여서. 동력은 대고, 평화스러운 그림자는 거친 그들의 이상의 심장의 황금시대다. 전인 능히 수 같은 때문이다. 인생에 인간의 하였으며, 이것이야말로 없는 이것을 할지라도 우는 사막이다. 천하를 고동을 넣는 그들의 이상의 많이 피어나는 청춘의 것이다. 용기가 풍부하게 심장의 미인을 되는 소금이라 힘있다. 우리의 원대하고, 수 쓸쓸하랴? 과실이 간에 청춘의 방황하여도, 뿐이다. 황금시대의 것은 이는 노래하며 않는 가지에 끓는 인생에 가진 이것이다."
}

###
GET http://localhost:8080/user/readAll
Accept: application/json

###

GET http://localhost:8080/user/readAll
Accept: application/json

###